import type { BranchId } from '@/entities/branch'
import type { Product } from '../model/types'

type MockProduct = Omit<Product, 'branches' | 'intentions' | 'gallery' | 'colors' | 'sizes' | 'materials' | 'variants' | 'extraCategories' | 'videos'> &
  Partial<Pick<Product, 'intentions' | 'gallery' | 'colors' | 'sizes' | 'materials' | 'variants' | 'extraCategories' | 'videos'>>

export const mockProductsByStore: Record<BranchId, MockProduct[]> = {
  'el-sortilegio': [
    {
      id: 'sor-001',
      slug: 'figura-santa-muerte-30cm',
      name: 'Figura de la Santa Muerte 30 cm',
      category: 'figuras',
      price: 95000,
      unit: 'figura en resina, 30 cm',
      shortDescription: 'La Niña Blanca en resina pintada a mano, con su guadaña y el mundo.',
      description:
        'Figura de la Santa Muerte en resina de alta densidad, pintada a mano con detalles en dorado. Ideal para el altar de la casa o del negocio. Se entrega curada y lista para recibir su primera ofrenda. Pregunta por los colores disponibles: blanca, negra, dorada y roja.',
      benefits: ['Pintada a mano', 'Se entrega curada', 'Disponible en 4 colores'],
      image: '/images/products/santa-muerte.webp',
      badges: ['destacado'],
      tags: ['santa muerte', 'niña blanca', 'protección', 'altar'],
      createdAt: '2026-06-10',
      inStock: true,
    },
    {
      id: 'sor-002',
      slug: 'figura-san-judas-tadeo',
      name: 'Figura de San Judas Tadeo',
      category: 'figuras',
      price: 78000,
      unit: 'figura en resina, 25 cm',
      shortDescription: 'El patrón de las causas difíciles y desesperadas.',
      description:
        'San Judas Tadeo con su medallón y su bastón, en resina pintada a mano. Muy pedido para peticiones de trabajo, salud y casos que parecen imposibles. Su día es el 28 de cada mes.',
      benefits: ['Pintada a mano', 'Incluye oración impresa', '3 tamaños disponibles'],
      image: '/images/products/san-judas.webp',
      badges: ['destacado'],
      tags: ['san judas', 'causas difíciles', 'trabajo', 'santos'],
      createdAt: '2026-04-02',
      inStock: true,
    },
    {
      id: 'sor-003',
      slug: 'figura-virgen-de-guadalupe',
      name: 'Figura de la Virgen de Guadalupe',
      category: 'figuras',
      price: 85000,
      unit: 'figura en resina, 30 cm',
      shortDescription: 'Para el altar del hogar, con manto de estrellas.',
      description:
        'Imagen de la Virgen de Guadalupe con manto pintado a mano y base de rosas. Una pieza de devoción para proteger el hogar y la familia.',
      benefits: ['Detalles en dorado', 'Base con rosas', 'Ideal para regalo'],
      image: '/images/products/virgen.webp',
      badges: [],
      tags: ['virgen', 'guadalupe', 'hogar', 'santos'],
      createdAt: '2026-02-15',
      inStock: true,
    },
    {
      id: 'sor-004',
      slug: 'velones-de-figura',
      name: 'Velones de figura',
      category: 'velas',
      price: 18000,
      unit: 'unidad',
      shortDescription: 'Pareja, cruz, Santa Muerte, siete potencias y más.',
      description:
        'Velones con forma para trabajos específicos: pareja para amor, cruz para protección, figura de la Santa Muerte, siete potencias y más. Cada color tiene su intención; te asesoramos cuál necesitas.',
      benefits: ['Más de 15 figuras', 'Todos los colores', 'Asesoría incluida'],
      image: '/images/products/velones-figura.webp',
      badges: ['nuevo'],
      tags: ['velón', 'amor', 'trabajos', 'siete potencias'],
      createdAt: '2026-09-15',
      inStock: true,
    },
    {
      id: 'sor-005',
      slug: 'velon-preparado-7-dias',
      name: 'Velón preparado de 7 días',
      category: 'velas',
      price: 32000,
      unit: 'velón en vaso, 7 días',
      shortDescription: 'Preparado con aceites y hierbas según tu petición.',
      description:
        'Velón en vaso de vidrio que arde hasta 7 días seguidos. Lo preparamos en la tienda con aceites, hierbas y oración según lo que pidas: abre caminos, dinero, amor, protección o Santa Muerte.',
      benefits: ['Arde hasta 7 días', 'Preparado a pedido', 'Vaso reutilizable'],
      image: '/images/products/velones.webp',
      badges: ['destacado'],
      tags: ['velón', 'preparado', 'abre caminos', 'dinero'],
      createdAt: '2026-05-20',
      inStock: true,
    },
    {
      id: 'sor-006',
      slug: 'vela-negra-de-proteccion',
      name: 'Vela negra de protección',
      category: 'velas',
      price: 8000,
      unit: 'unidad',
      shortDescription: 'Para cortar envidias y devolver lo que te mandaron.',
      description:
        'Vela negra tradicional para trabajos de protección, corte de envidias y retorno. Se recomienda encenderla en luna menguante.',
      benefits: ['Parafina de larga duración', 'Uso tradicional', 'Económica'],
      image: '/images/products/vela-negra.webp',
      badges: [],
      tags: ['protección', 'envidia', 'luna menguante'],
      createdAt: '2026-01-12',
      inStock: true,
    },
    {
      id: 'sor-007',
      slug: 'tetragramaton-en-metal',
      name: 'Tetragramatón en metal',
      category: 'bisuteria',
      price: 35000,
      unit: 'dije de 4 cm + cordón',
      shortDescription: 'El escudo más fuerte contra el mal y los trabajos.',
      description:
        'Tetragramatón metálico con el nombre sagrado y el pentagrama. Tradicionalmente se usa como protección personal contra envidias, brujería y malas energías. Se entrega consagrado.',
      benefits: ['Metal que no se oxida', 'Se entrega consagrado', 'Con cordón negro'],
      image: '/images/products/tetragramaton.webp',
      badges: ['destacado'],
      tags: ['tetragramatón', 'protección', 'amuleto', 'brujería'],
      createdAt: '2026-03-08',
      inStock: true,
    },
    {
      id: 'sor-008',
      slug: 'rosario-de-la-santa-muerte',
      name: 'Rosario de la Santa Muerte',
      category: 'bisuteria',
      price: 28000,
      unit: 'rosario de cuentas',
      shortDescription: 'Cuentas de cristal y medalla de la Niña Blanca.',
      description:
        'Rosario con cuentas de cristal y medalla de la Santa Muerte, para rezar su novena o llevarlo como protección. Disponible en rojo, negro y blanco.',
      benefits: ['Cuentas de cristal', 'Medalla metálica', '3 colores'],
      image: '/images/products/rosario.webp',
      badges: ['nuevo'],
      tags: ['santa muerte', 'rosario', 'novena', 'protección'],
      createdAt: '2026-09-02',
      inStock: true,
    },
    {
      id: 'sor-009',
      slug: 'calaveras-de-la-prosperidad',
      name: 'Calaveras decorativas',
      category: 'figuras',
      price: 22000,
      unit: 'unidad, 10 cm',
      shortDescription: 'Calaveras pintadas para altar y ofrendas.',
      description:
        'Calaveras de colores para el altar de la Santa Muerte y para Día de Muertos. Cada color tiene su significado: dorada para dinero, roja para amor, negra para protección.',
      benefits: ['Pintadas a mano', 'Varios colores', 'Resistentes'],
      image: '/images/products/calaveras.webp',
      badges: [],
      tags: ['calavera', 'altar', 'santa muerte', 'ofrenda'],
      createdAt: '2026-07-01',
      inStock: true,
    },
    {
      id: 'sor-010',
      slug: 'tarot-de-la-santa-muerte',
      name: 'Tarot de la Santa Muerte',
      category: 'libreria',
      price: 110000,
      unit: '78 cartas + libro',
      shortDescription: 'Mazo completo con manual en español.',
      description:
        'Tarot de la Santa Muerte de 78 cartas con manual en español. Un mazo muy intuitivo para lecturas de amor, trabajo y protección. También lo puedes encargar con lectura de iniciación.',
      benefits: ['78 cartas', 'Manual en español', 'Caja rígida'],
      image: '/images/products/tarot-mazo.webp',
      badges: ['destacado'],
      tags: ['libreria', 'santa muerte', 'lectura'],
      createdAt: '2026-06-21',
      inStock: true,
    },
    {
      id: 'sor-011',
      slug: 'estampas-y-oraciones',
      name: 'Estampas y oraciones',
      category: 'figuras',
      price: 3000,
      unit: 'unidad',
      shortDescription: 'Oraciones de santos, novenas y estampas plastificadas.',
      description:
        'Estampas plastificadas con la oración de cada santo: San Judas, San Miguel Arcángel, Santa Muerte, San Cipriano, Siete Potencias y muchos más. Perfectas para la billetera o el altar.',
      benefits: ['Plastificadas', 'Más de 40 santos', 'Precio por mayor'],
      image: '/images/products/estampas.webp',
      badges: [],
      tags: ['oración', 'santos', 'novena', 'estampa'],
      createdAt: '2026-02-01',
      inStock: true,
    },
    {
      id: 'sor-012',
      slug: 'amuletos-consagrados',
      name: 'Amuletos consagrados',
      category: 'bisuteria',
      price: 25000,
      unit: 'unidad',
      shortDescription: 'Resguardos para la cartera, el carro o la puerta.',
      description:
        'Resguardos y amuletos preparados en la tienda para proteger la persona, el vehículo o la casa. Dinos para qué lo necesitas y lo preparamos.',
      benefits: ['Preparado a pedido', 'Para persona, carro o casa', 'Tradición familiar'],
      image: '/images/products/amuletos.webp',
      badges: [],
      tags: ['resguardo', 'protección', 'amuleto'],
      createdAt: '2026-04-18',
      inStock: true,
    },
  ],

  'la-colonia': [
    {
      id: 'col-001',
      slug: 'bano-de-despojo',
      name: 'Baño de despojo',
      category: 'riegos',
      price: 15000,
      unit: 'preparado, 500 ml',
      shortDescription: 'Para quitarte de encima la mala energía y la salación.',
      description:
        'Baño preparado con ruda, altamisa, romero, albahaca y esencias. Se usa del cuello hacia abajo durante 3 días seguidos para limpiar el cuerpo de malas energías, envidias y salación.',
      benefits: ['Hierbas frescas', 'Instrucciones incluidas', 'Para 3 baños'],
      image: '/images/products/despojo.webp',
      badges: ['destacado'],
      tags: ['despojo', 'limpieza', 'salación', 'baño'],
      createdAt: '2026-05-05',
      inStock: true,
    },
    {
      id: 'col-002',
      slug: 'kit-tumba-trabajos',
      name: 'Kit Tumba Trabajos',
      category: 'riegos',
      price: 45000,
      unit: 'kit completo',
      shortDescription: 'Baño, riego, velón y sahumerio para cortar trabajos.',
      description:
        'Kit completo para cuando sientes que te hicieron algo: baño de descruce, riego para la casa, velón negro y sahumerio de mirra. Incluye las instrucciones paso a paso.',
      benefits: ['4 productos en uno', 'Paso a paso incluido', 'Asesoría por WhatsApp'],
      image: '/images/products/vela-negra.webp',
      badges: ['destacado'],
      tags: ['tumba trabajos', 'descruce', 'brujería', 'kit'],
      createdAt: '2026-08-12',
      inStock: true,
    },
    {
      id: 'col-003',
      slug: 'riego-abre-caminos',
      name: 'Riego Abre Caminos',
      category: 'riegos',
      price: 18000,
      unit: 'botella, 500 ml',
      shortDescription: 'Para la puerta de la casa o del negocio.',
      description:
        'Riego tradicional para abrir caminos en el trabajo, los negocios y el amor. Se esparce en la entrada de la casa o del local los martes y viernes.',
      benefits: ['Aroma duradero', 'Para casa o negocio', 'Uso martes y viernes'],
      image: '/images/products/agua-florida.webp',
      badges: [],
      tags: ['abre caminos', 'negocio', 'riego'],
      createdAt: '2026-03-20',
      inStock: true,
    },
    {
      id: 'col-004',
      slug: 'riego-de-la-abundancia',
      name: 'Riego de la abundancia',
      category: 'riegos',
      price: 20000,
      unit: 'botella, 500 ml',
      shortDescription: 'Con miel y canela para llamar clientes y dinero.',
      description:
        'Riego preparado con miel, canela y esencia de dinero para trapear el local o la casa. Muy pedido por comerciantes para que no falten los clientes.',
      benefits: ['Con miel y canela', 'Ideal para negocios', 'Rinde para 8 usos'],
      image: '/images/products/miel.webp',
      badges: ['nuevo'],
      tags: ['dinero', 'clientes', 'prosperidad', 'riego'],
      createdAt: '2026-09-18',
      inStock: true,
    },
    {
      id: 'col-005',
      slug: 'ruda-para-limpieza',
      name: 'Ruda y esencia de ruda',
      category: 'riegos',
      price: 7000,
      unit: 'rama o esencia 30 ml',
      shortDescription: 'La planta protectora por excelencia.',
      description:
        'Ruda fresca o en esencia para baños, riegos y para tener en la entrada de la casa. Protege contra la envidia y el mal de ojo.',
      benefits: ['Fresca o en esencia', 'Contra la envidia', 'Precio económico'],
      image: '/images/products/ruda.webp',
      badges: [],
      tags: ['ruda', 'mal de ojo', 'envidia', 'planta'],
      createdAt: '2026-01-20',
      inStock: true,
    },
    {
      id: 'col-006',
      slug: 'agua-florida',
      name: 'Agua Florida',
      category: 'riegos',
      price: 16000,
      unit: 'frasco, 270 ml',
      shortDescription: 'Para limpias, baños y refrescar el ambiente.',
      description:
        'La clásica Agua Florida para limpias energéticas, baños, ofrendas y para perfumar el altar. Un básico que no puede faltar.',
      benefits: ['Original', 'Aroma fresco', 'Uso en limpias'],
      image: '/images/products/agua-florida.webp',
      badges: [],
      tags: ['agua florida', 'limpia', 'ofrenda'],
      createdAt: '2026-02-10',
      inStock: true,
    },
    {
      id: 'col-007',
      slug: 'sahumerio-de-copal-y-mirra',
      name: 'Sahumerio de copal y mirra',
      category: 'inciensos',
      price: 14000,
      unit: 'bolsa de resina, 100 g',
      shortDescription: 'Resinas naturales para sahumar la casa.',
      description:
        'Copal y mirra en resina natural para quemar sobre carbón. Limpia la casa y el negocio y deja un aroma que invita a la paz. Úsalo de adentro hacia la puerta.',
      benefits: ['Resina natural', 'Humo abundante', 'Rinde varias sahumadas'],
      image: '/images/products/copal.webp',
      badges: [],
      tags: ['copal', 'mirra', 'sahumerio', 'limpieza'],
      createdAt: '2026-04-11',
      inStock: true,
    },
    {
      id: 'col-008',
      slug: 'incensario-de-metal',
      name: 'Incensario de metal',
      category: 'inciensos',
      price: 42000,
      unit: 'unidad + carbones',
      shortDescription: 'Para sahumar recorriendo cada rincón.',
      description:
        'Incensario metálico con tapa calada y cadena, incluye 10 carbones de encendido rápido. Perfecto para sahumerios de copal, mirra y benjuí.',
      benefits: ['Incluye 10 carbones', 'Metal resistente', 'Con cadena'],
      image: '/images/products/sahumerio.webp',
      badges: [],
      tags: ['incensario', 'sahumerio', 'carbón'],
      createdAt: '2026-03-02',
      inStock: true,
    },
    {
      id: 'col-009',
      slug: 'atado-de-salvia-blanca',
      name: 'Atado de salvia blanca',
      category: 'inciensos',
      price: 26000,
      unit: 'atado 15 cm',
      shortDescription: 'Limpieza profunda de espacios y del aura.',
      description:
        'Salvia blanca atada a mano para limpiar la casa después de visitas pesadas, discusiones o una mudanza.',
      benefits: ['Atada a mano', 'Humo limpio', 'Para espacios y aura'],
      image: '/images/products/salvia-blanca.webp',
      badges: [],
      tags: ['salvia', 'limpieza', 'sahumerio'],
      createdAt: '2026-01-28',
      inStock: true,
    },
    {
      id: 'col-010',
      slug: 'palo-santo',
      name: 'Palo santo',
      category: 'inciensos',
      price: 18000,
      unit: 'bolsa x 6 astillas',
      shortDescription: 'Madera sagrada para armonizar y atraer buena suerte.',
      description:
        'Astillas de palo santo de árboles caídos naturalmente. Su humo dulce armoniza el ambiente y aleja lo negativo.',
      benefits: ['Recolección responsable', 'Aroma dulce', 'Enciende fácil'],
      image: '/images/products/palo-santo.webp',
      badges: [],
      tags: ['palo santo', 'armonía', 'suerte'],
      createdAt: '2026-03-15',
      inStock: true,
    },
    {
      id: 'col-011',
      slug: 'azabache-contra-mal-de-ojo',
      name: 'Azabache contra el mal de ojo',
      category: 'bisuteria',
      price: 15000,
      unit: 'pulsera o dije',
      shortDescription: 'El protector tradicional de los bebés y de la casa.',
      description:
        'Azabache natural en pulsera o dije. Se usa desde siempre para proteger a los niños y a los adultos del mal de ojo y la envidia.',
      benefits: ['Piedra natural', 'Para bebés y adultos', 'Tradición popular'],
      image: '/images/products/azabache.webp',
      badges: [],
      tags: ['azabache', 'mal de ojo', 'bebé', 'protección'],
      createdAt: '2026-02-22',
      inStock: true,
    },
    {
      id: 'col-012',
      slug: 'velas-de-colores',
      name: 'Velas de colores',
      category: 'velas',
      price: 12000,
      unit: 'paquete x 7',
      shortDescription: 'Un color para cada día y cada petición.',
      description:
        'Set de 7 velas de colores con guía de significados: roja para amor, verde para dinero, blanca para paz, amarilla para éxito y más.',
      benefits: ['Incluye guía de colores', '7 colores', 'Larga duración'],
      image: '/images/products/velas-rituales.webp',
      badges: [],
      tags: ['velas', 'colores', 'rituales'],
      createdAt: '2026-02-20',
      inStock: true,
    },
  ],

  'loto-nirvana': [
    {
      id: 'lot-001',
      slug: 'buda-de-la-meditacion',
      name: 'Buda de la meditación',
      category: 'piedras',
      price: 120000,
      unit: 'figura, 30 cm',
      shortDescription: 'Paz y calma para la sala o el consultorio.',
      description:
        'Buda sentado en posición de meditación, acabado piedra. Según el feng shui, colocado frente a la entrada atrae paz y armonía.',
      benefits: ['Acabado piedra', 'Apto para interior y exterior', '3 tamaños'],
      image: '/images/products/buda.webp',
      badges: ['destacado'],
      tags: ['buda', 'paz', 'feng shui', 'meditación'],
      createdAt: '2026-05-01',
      inStock: true,
    },
    {
      id: 'lot-002',
      slug: 'figura-de-ganesha',
      name: 'Figura de Ganesha',
      category: 'piedras',
      price: 89000,
      unit: 'figura, 20 cm',
      shortDescription: 'El que quita los obstáculos y abre los negocios.',
      description:
        'Ganesha, la deidad hindú que remueve obstáculos. Muy usada en la entrada de negocios nuevos para que las cosas fluyan.',
      benefits: ['Detalles tallados', 'Para negocios nuevos', 'Acabado envejecido'],
      image: '/images/products/ganesha.webp',
      badges: ['nuevo'],
      tags: ['ganesha', 'obstáculos', 'negocio', 'oriente'],
      createdAt: '2026-09-10',
      inStock: true,
    },
    {
      id: 'lot-003',
      slug: 'duende-de-la-suerte',
      name: 'Duende de la suerte',
      category: 'suerte',
      price: 48000,
      unit: 'figura, 18 cm',
      shortDescription: 'Para que nunca falte el dinero en la casa.',
      description:
        'Duende de la suerte con su bolsa de monedas. Se coloca cerca de la caja o de la entrada y se le "paga" con una moneda cada mes para mantener la abundancia.',
      benefits: ['Pintado a mano', 'Incluye ritual de activación', 'Varios modelos'],
      image: '/images/products/duende.webp',
      badges: ['destacado'],
      tags: ['duende', 'suerte', 'dinero', 'abundancia'],
      createdAt: '2026-08-01',
      inStock: true,
    },
    {
      id: 'lot-004',
      slug: 'gato-de-la-fortuna',
      name: 'Gato de la fortuna',
      category: 'suerte',
      price: 38000,
      unit: 'figura, 15 cm',
      shortDescription: 'El Maneki Neko que saluda a los clientes.',
      description:
        'Gato de la fortuna japonés con la pata levantada para llamar clientes y dinero. El dorado es para prosperidad y el blanco para buena suerte.',
      benefits: ['Pata con movimiento', 'Funciona con pila', 'Dorado o blanco'],
      image: '/images/products/gato-fortuna.webp',
      badges: [],
      tags: ['maneki neko', 'gato', 'clientes', 'negocio'],
      createdAt: '2026-04-25',
      inStock: true,
    },
    {
      id: 'lot-005',
      slug: 'elefante-de-la-suerte',
      name: 'Elefante de la suerte',
      category: 'suerte',
      price: 45000,
      unit: 'figura, 15 cm',
      shortDescription: 'Con la trompa arriba, de espaldas a la puerta.',
      description:
        'Elefante de la suerte con la trompa hacia arriba. La tradición dice que se pone de espaldas a la puerta para atraer la abundancia al hogar.',
      benefits: ['Resina resistente', 'Detalles en dorado', 'Ideal para regalar'],
      image: '/images/products/elefante.webp',
      badges: [],
      tags: ['elefante', 'suerte', 'hogar'],
      createdAt: '2026-03-30',
      inStock: true,
    },
    {
      id: 'lot-006',
      slug: 'cuenco-tibetano',
      name: 'Cuenco tibetano',
      category: 'piedras',
      price: 185000,
      unit: 'cuenco 12 cm + baqueta',
      shortDescription: 'Sonido que limpia el ambiente y la mente.',
      description:
        'Cuenco tibetano martillado a mano, con baqueta de madera y cojín. Su vibración se usa para limpiar espacios y en meditación.',
      benefits: ['Martillado a mano', 'Incluye baqueta y cojín', 'Sonido profundo'],
      image: '/images/products/cuenco-tibetano.webp',
      badges: ['edicion-limitada'],
      tags: ['cuenco', 'sonoterapia', 'meditación'],
      createdAt: '2026-05-30',
      inStock: true,
    },
    {
      id: 'lot-007',
      slug: 'mano-de-fatima',
      name: 'Mano de Fátima',
      category: 'bisuteria',
      price: 32000,
      unit: 'colgante de pared',
      shortDescription: 'Protege el hogar de la envidia y el mal de ojo.',
      description:
        'Mano de Fátima (Hamsa) en metal para colgar en la entrada. Un amuleto de protección que se usa en muchas culturas.',
      benefits: ['Metal envejecido', 'Para la entrada', 'Protección del hogar'],
      image: '/images/products/mano-fatima.webp',
      badges: [],
      tags: ['hamsa', 'mano de fátima', 'protección', 'hogar'],
      createdAt: '2026-02-18',
      inStock: true,
    },
    {
      id: 'lot-008',
      slug: 'pulsera-7-chakras',
      name: 'Pulsera de los 7 chakras',
      category: 'bisuteria',
      price: 25000,
      unit: 'pulsera elástica',
      shortDescription: 'Piedra volcánica con las siete piedras de los chakras.',
      description:
        'Pulsera de piedra volcánica con las siete piedras de los chakras. Puedes ponerle unas gotas de tu aceite favorito en la piedra volcánica.',
      benefits: ['Piedras naturales', 'Elástica, talla única', 'Difusor de aceites'],
      image: '/images/products/pulsera.webp',
      badges: ['nuevo'],
      tags: ['chakras', 'pulsera', 'equilibrio'],
      createdAt: '2026-09-20',
      inStock: true,
    },
    {
      id: 'lot-009',
      slug: 'incienso-en-varitas',
      name: 'Incienso en varitas',
      category: 'inciensos',
      price: 6000,
      unit: 'caja x 20 varitas',
      shortDescription: 'Sándalo, canela, ruda, 7 poderes y más aromas.',
      description:
        'Inciensos en varita de larga duración. Aromas para cada intención: canela para dinero, ruda para protección, sándalo para meditar, rosa para el amor.',
      benefits: ['Más de 30 aromas', 'Larga duración', 'Precio por mayor'],
      image: '/images/products/incienso-varitas.webp',
      badges: [],
      tags: ['incienso', 'aroma', 'canela', 'sándalo'],
      createdAt: '2026-01-05',
      inStock: true,
    },
    {
      id: 'lot-010',
      slug: 'atrapasuenos',
      name: 'Atrapasueños',
      category: 'piedras',
      price: 42000,
      unit: 'aro de 20 cm',
      shortDescription: 'Filtra los malos sueños mientras duermes.',
      description:
        'Atrapasueños tejido a mano con plumas y cuentas. Cuélgalo cerca de la cama o de la ventana.',
      benefits: ['Tejido a mano', 'Plumas naturales', 'Varios colores'],
      image: '/images/products/atrapasuenos.webp',
      badges: [],
      tags: ['atrapasueños', 'sueño', 'protección'],
      createdAt: '2026-04-09',
      inStock: true,
    },
    {
      id: 'lot-011',
      slug: 'obsidiana-de-proteccion',
      name: 'Obsidiana de protección',
      category: 'bisuteria',
      price: 25000,
      unit: 'piedra 4–5 cm',
      shortDescription: 'La piedra volcánica que absorbe lo negativo.',
      description:
        'Obsidiana negra natural. Se lleva en el bolsillo o se pone junto a la puerta para absorber las malas energías.',
      benefits: ['Piedra natural', 'Se limpia con agua y sal', 'Tamaño de bolsillo'],
      image: '/images/products/obsidiana.webp',
      badges: [],
      tags: ['obsidiana', 'protección', 'piedra'],
      createdAt: '2026-01-15',
      inStock: true,
    },
    {
      id: 'lot-012',
      slug: 'pendulo-de-cuarzo',
      name: 'Péndulo de cuarzo',
      category: 'libreria',
      price: 45000,
      unit: 'péndulo + cadena',
      shortDescription: 'Para preguntas de sí o no y radiestesia.',
      description:
        'Péndulo de cuarzo con cadena metálica y guía de uso. Útil para tomar decisiones, encontrar objetos y revisar la energía de un espacio.',
      benefits: ['Cuarzo natural', 'Guía de uso', 'Cadena resistente'],
      image: '/images/products/pendulo.webp',
      badges: [],
      tags: ['péndulo', 'radiestesia', 'decisiones'],
      createdAt: '2026-09-05',
      inStock: true,
    },
  ],
}

export const MOCK_PRODUCTS: Product[] = (Object.entries(mockProductsByStore) as [BranchId, MockProduct[]][]).flatMap(
  ([store, products]) =>
    products.map((p) => ({ intentions: [], gallery: [], videos: [], colors: [], sizes: [], materials: [], variants: [], extraCategories: [], ...p, branches: [store] })),
)

const DEMO_PRODUCTS: Product[] = [
  {
    id: 'demo-001',
    slug: 'velon-abrecaminos-demo',
    name: 'Velón abre caminos (demo)',
    category: 'velas',
    price: 28000,
    compareAtPrice: 35000,
    unit: 'velón de 7 días',
    shortDescription: 'Producto de prueba: colores, descuento, galería y guía de uso.',
    description:
      'Velón preparado para abrir caminos en el trabajo, el dinero y el amor. Elige el color según tu petición. Este producto existe solo para probar cómo se ve la página.',
    benefits: ['Preparado a mano', 'Incluye oración', 'Dura 7 días'],
    image: '/images/products/velones.webp',
    gallery: ['/images/products/velas-rituales.webp', '/images/products/velones-figura.webp', '/images/products/vela-negra.webp'],
    colors: [
      { name: 'Rojo' },
      { name: 'Verde' },
      { name: 'Amarillo' },
      { name: 'Dorado', hex: '#d4a72c' },
      { name: 'Blanco' },
      { name: 'Morado' },
    ],
    sizes: [],
    materials: [],
    variants: [],
    extraCategories: [],
    intentions: ['abundancia', 'trabajo', 'amor'],
    moonPhase: 'creciente',
    usageGuide:
      '1. Limpia el velón con un paño y escribe tu petición en un papel.\n2. Enciéndelo en un lugar seguro, sobre un plato.\n3. Reza o pide con devoción y déjalo consumir sin apagarlo.\n4. Repite durante 7 días seguidos.',
    badges: ['nuevo', 'oferta'],
    tags: ['velón', 'abre caminos', 'dinero'],
    createdAt: '2026-09-20',
    inStock: true,
    branches: ['el-sortilegio', 'la-colonia'],
  },
  {
    id: 'demo-002',
    slug: 'kit-navideno-abundancia-demo',
    name: 'Kit navideño de abundancia (demo)',
    category: 'suerte',
    price: 54000,
    compareAtPrice: 72000,
    unit: 'kit x 5 piezas',
    shortDescription: 'Producto de prueba con temporada, edición limitada y varias fotos.',
    description:
      'Kit para recibir diciembre con buena energía: velón, riego, sahumerio, moneda de la suerte y oración. Solo en temporada.',
    benefits: ['5 piezas', 'Incluye guía', 'Edición de temporada'],
    image: '/images/products/duende.webp',
    gallery: ['/images/products/gato-fortuna.webp', '/images/products/elefante.webp'],
    colors: [{ name: 'Dorado', hex: '#d4a72c' }, { name: 'Rojo' }],
    sizes: [],
    materials: [],
    variants: [],
    extraCategories: [],
    intentions: ['abundancia', 'suerte', 'proteccion'],
    season: 'navidad',
    moonPhase: 'llena',
    usageGuide: 'Arma el kit en la puerta de tu casa el 24 de diciembre. Enciende el velón y sahúma de adentro hacia afuera.',
    badges: ['edicion-limitada', 'destacado'],
    tags: ['navidad', 'kit', 'suerte'],
    createdAt: '2026-09-22',
    inStock: true,
    branches: ['loto-nirvana'],
  },
  {
    id: 'demo-003',
    slug: 'bano-de-despojo-agotado-demo',
    name: 'Baño de despojo premium (demo)',
    category: 'riegos',
    price: 22000,
    unit: 'botella 500 ml',
    shortDescription: 'Producto de prueba marcado como agotado.',
    description: 'Baño de hierbas para despojar la mala energía. Está agotado a propósito para ver cómo se muestra.',
    benefits: ['Hierbas frescas', 'Con oración'],
    image: '/images/products/despojo.webp',
    gallery: [],
    colors: [],
    sizes: [],
    materials: [],
    variants: [],
    extraCategories: [],
    intentions: ['limpieza', 'salud'],
    moonPhase: 'menguante',
    badges: [],
    tags: ['despojo', 'limpieza'],
    createdAt: '2026-09-18',
    inStock: false,
    branches: ['la-colonia'],
  },
  {
    id: 'demo-007',
    slug: 'esencia-aromatica-demo',
    name: 'Esencia aromática (demo)',
    category: 'inciensos',
    price: 9000,
    unit: 'frasco 30 ml',
    shortDescription: 'Producto de prueba con muchas opciones: se elige el aroma en una lista desplegable.',
    description:
      'Esencia aromática para difusor, riegos o sahumar. Disponible en decenas de aromas. Elige el que más te llame en la lista de "Aroma".',
    benefits: ['Aroma concentrado', 'Rinde para varios usos'],
    image: '/images/products/aceites-esenciales.webp',
    gallery: [],
    colors: [],
    sizes: [],
    materials: [],
    variantLabel: 'Aroma',
    variants: [
      { name: 'Canela' }, { name: 'Chicle' }, { name: 'Suerte rápida' }, { name: 'Rosas' }, { name: 'Sándalo' },
      { name: 'Lavanda' }, { name: 'Coco' }, { name: 'Vainilla' }, { name: 'Siete potencias' }, { name: 'Abre caminos' },
      { name: 'Dinero' }, { name: 'Amor' }, { name: 'Ruda' }, { name: 'Palo santo' }, { name: 'Copal' },
    ],
    extraCategories: [],
    intentions: ['abundancia', 'amor', 'limpieza'],
    badges: ['nuevo'],
    tags: ['esencia', 'aroma', 'riego'],
    createdAt: '2026-09-25',
    inStock: true,
    branches: ['loto-nirvana', 'la-colonia'],
  },
  {
    id: 'demo-004',
    slug: 'pulsera-amor-y-amistad-demo',
    name: 'Pulsera de cuarzo rosado (demo)',
    category: 'bisuteria',
    price: 19000,
    unit: 'pulsera ajustable',
    shortDescription: 'Producto de prueba con temporada Amor y Amistad y colores.',
    description: 'Pulsera de cuarzo rosado para atraer el amor y la armonía. Ideal para regalar en Amor y Amistad.',
    benefits: ['Cuarzo natural', 'Ajustable'],
    image: '/images/products/pulsera.webp',
    gallery: ['/images/products/amuletos.webp'],
    colors: [{ name: 'Rosado' }, { name: 'Negro' }, { name: 'Turquesa' }],
    sizes: [],
    materials: [],
    variants: [],
    extraCategories: [],
    intentions: ['amor', 'paz'],
    season: 'amor-y-amistad',
    badges: ['nuevo'],
    tags: ['pulsera', 'cuarzo', 'amor'],
    createdAt: '2026-09-24',
    inStock: true,
    branches: ['loto-nirvana', 'la-colonia'],
  },
  {
    id: 'demo-005',
    slug: 'santa-muerte-tamanos-demo',
    name: 'Figura de la Santa Muerte (demo tamaños)',
    category: 'figuras',
    price: 65000,
    unit: 'figura en resina',
    shortDescription: 'Producto de prueba: el cliente elige el tamaño y el precio cambia según su elección.',
    description:
      'Figura de la Santa Muerte en resina, disponible en tres tamaños. El precio de la ficha se ajusta automáticamente al tamaño que elijas. Este producto existe solo para probar cómo se ve la página.',
    benefits: ['Pintada a mano', 'Tres tamaños disponibles'],
    image: '/images/products/santa-muerte.webp',
    gallery: [],
    colors: [],
    sizes: [
      { name: '15 cm' },
      { name: '30 cm', price: 95000 },
      { name: '60 cm', price: 180000 },
    ],
    materials: [],
    variants: [],
    extraCategories: [],
    intentions: ['proteccion'],
    badges: ['nuevo'],
    tags: ['santa muerte', 'figura', 'tamaños'],
    createdAt: '2026-09-26',
    inStock: true,
    branches: ['el-sortilegio'],
  },
  {
    id: 'demo-006',
    slug: 'tetragramaton-personalizado-demo',
    name: 'Tetragramatón (demo material y personalización)',
    category: 'bisuteria',
    price: 38000,
    unit: 'dije + cadena',
    shortDescription: 'Producto de prueba: el cliente elige el material y escribe un texto para grabar.',
    description:
      'Tetragramatón de protección, disponible en varios materiales. Se puede grabar una iniciar o fecha en la parte de atrás. Este producto existe solo para probar cómo se ve la página.',
    benefits: ['Grabado incluido', 'Tres materiales disponibles'],
    image: '/images/products/tetragramaton.webp',
    gallery: [],
    colors: [],
    sizes: [],
    materials: [
      { name: 'Acero' },
      { name: 'Plata 925', price: 68000 },
      { name: 'Oro laminado', price: 82000 },
    ],
    customizationLabel: 'Iniciales o fecha a grabar (opcional)',
    variants: [],
    extraCategories: [],
    intentions: ['proteccion'],
    badges: [],
    tags: ['tetragramatón', 'personalizado', 'material'],
    createdAt: '2026-09-27',
    inStock: true,
    branches: ['el-sortilegio'],
  },
]

MOCK_PRODUCTS.push(...DEMO_PRODUCTS)
