import {
  Bath,
  BookOpen,
  Church,
  Crown,
  FlaskConical,
  Medal,
  Skull,
  Sprout,
  SprayCan,
  TestTube,
  WandSparkles,
  Clover,
  Droplets,
  Flame,
  Flower2,
  Gem,
  Heart,
  Leaf,
  Moon,
  Shield,
  Sparkles,
  Star,
  Sun,
  Wind,
  type LucideIcon,
} from 'lucide-react'

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  church: Church,
  flame: Flame,
  droplets: Droplets,
  wind: Wind,
  shield: Shield,
  clover: Clover,
  flower: Flower2,
  sparkles: Sparkles,
  gem: Gem,
  heart: Heart,
  leaf: Leaf,
  moon: Moon,
  sun: Sun,
  star: Star,
  skull: Skull,
  medal: Medal,
  sprout: Sprout,
  crown: Crown,
  wand: WandSparkles,
  'spray-can': SprayCan,
  bath: Bath,
  book: BookOpen,
  flask: FlaskConical,
  'test-tube': TestTube,
}

export const resolveCategoryIcon = (key?: string): LucideIcon => CATEGORY_ICONS[key ?? ''] ?? Sparkles
